language: r

matrix:
  include:
    - dist: bionic
      r: release
      after_success: Rscript -e 'covr::codecov()'
    - dist: xenial
      r: devel
      # 3/8/2019 time checks are failing on R-devel
      # env: _R_CHECK_SYSTEM_CLOCK_ = 0 # removed 5/29/2020
    - osx_image: xcode11.6
      r: release
      # macOS 10.12 version - Fixing Travis build failure on 4/8/2020
      # osx_image: xcode9.2 # removed 5/29/2020

r_github_packages:
  - r-lib/covr

cache: packages

sudo: false
