language: r

matrix:
  include:
    - dist: xenial
      r: release
      after_success: Rscript -e 'covr::codecov()'
    - dist: trusty
      r: devel
      # 3/8/2019 time checks are failing on R-devel
      env: _R_CHECK_SYSTEM_CLOCK_ = 0
    - os: osx
      r: release

r_github_packages:
  - r-lib/covr

cache: packages

sudo: false
