---
title: "Triangle Distribution Math"
author: "Rob Carnell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
header-includes:
  - \usepackage{amsmath}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Triangle Notation

```{r triangle_drawing, echo=FALSE, fig.width=5, fig.height=4}
plot(c(-1,5), c(0,4), type = "n", xlab = "x", ylab = "f(x)", axes = FALSE)
lines(c(0,1), c(0,3), col = "red")
lines(c(1,4), c(3,0), col = "red")
axis(2, at = c(0,3), labels = c("0","h"), las = 2)
axis(1, at = c(0,1,4), labels = c("a", "c", "b"))
box()
```

- $a$ = minimum
- $b$ = maximum
- $c$ = mode
- $h$ = density at the mode = $\frac{2}{b-a}$

## Triangle PDF

$$f(x) =
\left\{
	\begin{array}{ll}
		\frac{h}{c-a}(x-a)  & \mbox{if } a \leq x \leq c \\
		\frac{h}{c-b}(x-b) & \mbox{if } c < x \leq b \\
		0 & \mbox{otherwise}
	\end{array}
\right.\ \ \ \ (1)$$

Integrating the pdf in equation (1) to solve for h

$$\int f(x) dx = \frac{h}{c-a}\int_{a}^{c} (x-a) dx + 
\frac{h}{c-b} \int_{c}^{b} (x-b) dx$$

$$=\frac{h}{c-a} \bigg[\frac{x^2}{2}-ax\bigg]_{a}^{c} + 
\frac{h}{c-b} \bigg[\frac{x^2}{2} - bx\bigg]_{c}^{b}$$

$$=\frac{h}{2(c-a)}\big[c^2-2ac-a^2+2a^2\big] + \frac{h}{2(c-b)}\big[b^2-2b^2-c^2+2bc\big]$$

$$=\frac{h}{2(c-a)(c-b)} \big[c^3-bc^2-2ac^2+2abc-a^2c+a^2b+2a^2c-2a^2b+b^2c-ab^2-2b^2c+2ab^2-c^3+ac^2+2bc^2-2abc\big]$$

$$=\frac{h}{2(c-a)(c-b)}\big[bc^2-ac^2+a^2c-a^2b-b^2c+ab^2+abc-abc\big]$$

$$=\frac{h}{2(c-a)(c-b)}\big[b(c^2-ac+ab-bc)-a(c^2-ac+ab-bc)\big]$$

$$=\frac{h}{2(c-a)(c-b)}\big[b(c-a)(c-b)-a(c-a)(c-b)\big]=\frac{h(b-a)}{2}=1$$

$$h=\frac{2}{b-a}\ \ \ \ (2)$$

Substituting back into equation (1),

$$f(x) =
\left\{
	\begin{array}{ll}
		\frac{2}{(b-a)(c-a)}(x-a)  & \mbox{if } a \leq x \leq c \\
		\frac{2}{(b-a)(c-b)}(x-b) & \mbox{if } c < x \leq b \\
		0 & \mbox{otherwise}
	\end{array}
\right.\ \ \ \ (3)$$

## Triangle Mean

Integrating equation (3) to find $E(x)$,

$$E(x)=\int xf(x)dx = \frac{h}{c-a}\int_a^c (x^2-ax) dx + 
\frac{h}{c-b}\int_c^b (x^2-bx) dx$$

$$=\frac{h}{c-a} \bigg[\frac{x^3}{3}-\frac{ax^2}{2}\bigg]_a^c +
\frac{h}{c-b} \bigg[\frac{x^3}{3}-\frac{bx^2}{2}\bigg]_c^b$$

$$=\frac{h}{6(c-a)}\big[2c^3-3ac^2+a^3\big] +
\frac{h}{6(c-b)}\big[-b^3-2c^3+3bc^2\big]$$

$$=\frac{h}{6(c-a)(c-b)}\big[2c^4-2bc^3-3ac^3+3abc^2+a^3c-a^3b -
b^3c+ab^3-2c^4+2ac^3+3bc^3-3abc^2\big]$$

$$=\frac{h}{6(c-a)(c-b)}\big[bc^3-ac^3+a^3c-a^3b-b^3c+ab^3\big]$$

$$=\frac{h}{6(c-a)(c-b)}\big[a(a^2c-a^2b)+b(-b^2c+ab^2)+c(bc^2-ac^2)\big]$$

$$=\frac{1}{3(c-a)(c-b)(b-a)} \big[(a(bc^2-abc+ab^2-b^2c-ac^2+a^2c-a^2b+abc) + b(bc^2-abc+ab^2-b^2c-ac^2+a^2c-a^2b+abc) +
c(bc^2-abc+ab^2-b^2c-ac^2+a^2c-a^2b+abc))\big]$$

$$=\frac{1}{3(c-a)(c-b)(b-a)}\big[a(c-a)(c-b)(b-a)+b(c-a)(c-b)(b-a)+c(c-a)(c-b)(b-a)\big]$$

$$=\frac{a+b+c}{3}\ \ \ \ (3)$$

## Logarithmic Triangle distribution

Define:

$$la=log_{\phi}(a),\ \ lb=log_{\phi}(b),\ \ lc=log_{\phi}(c),\ \ h=\frac{2}{lb-la}, \ \ \phi = \mbox{log base}$$

$$f(z) = 
\left\{
  \begin{array}{ll}
    \frac{h}{lc - la}(z - la) & \mbox{if } la \leq z \leq lc \\
    \frac{h}{lc - lb}(z - lb) & \mbox{if } lc < z \leq lb \\
    0 & \mbox{otherwise}
  \end{array}
\right.\ \ \ \ (4)$$

However,

$$E({\phi}^z) \neq {\phi}^{E(z)}\ \ \ \ (5)$$

Therefore, transforming...

$$Y={\phi}^Z$$

$$Z=log_{\phi}(Y)$$

$$w(y)=log_{\phi}(y)$$

$$w'(y)=\frac{dz}{dy} = \frac{1}{yln({\phi})}$$

$$g(y)=f(w(y))w'(y)$$

$$g(y) = 
\left\{
  \begin{array}{ll}
    \frac{2}{(lc-la)(lb-la)ln({\phi})}\frac{log_{\phi}(y) - la}{y} & \mbox{if } 0 < a \leq y \leq c \\
    \frac{2}{(lc-lb)(lb-la)ln({\phi})}\frac{lob_{\phi}(y) - lb}{y} & \mbox{if } c < y \leq b \\
    0 & \mbox{otherwise}
  \end{array}
\right.\ \ \ \ (5)$$

Define:

$$\beta_1=\frac{2}{(lc-la)(lb-la)}$$

$$\beta_2=\frac{2}{(lc-lb)(lb-la)}$$

Finding the CDF, 

$$G(y)=\int_{-\infty}^y g(y)dy$$

$$G(a \leq y \leq c) = \frac{\beta_1}{ln({\phi})} \int_a^y \frac{ln(y)}{yln({\phi})}-\frac{la}{y}dy$$

$$=\frac{\beta_1}{ln({\phi})} \bigg[\frac{ln^2(y)}{2ln({\phi})} - laln(y)\bigg]_a^y$$

$$=\frac{\beta_1}{ln({\phi})} \bigg[\frac{ln^2(y)}{2ln({\phi})} - laln(y) - 
\frac{ln^2(a)}{2ln({\phi})} + laln(a)\bigg]$$

$$=\beta_1 \bigg[\frac{log_{\phi}^2(y)}{2} - lalog_{\phi}(y) - \frac{la^2}{2} + la^2\bigg]$$

$$G(c < y \leq b) = G(c) + \frac{\beta_2}{ln({\phi})} \int_c^y \frac{ln(y)}{yln({\phi})} - \frac{lb}{y}dy$$

$$=G(c) + \frac{\beta_2}{ln({\phi})} \bigg[\frac{ln^2(y)}{2ln({\phi})} - lb ln(y)\bigg]_c^y$$

$$=G(c) + \frac{\beta_2}{ln({\phi})} \bigg[\frac{ln^2(y)}{2ln({\phi})} - lb ln(y) - 
\frac{ln^2(c)}{2ln({\phi})} + lb ln(c)\bigg]$$

$$=G(c) + \beta_2 \bigg[\frac{log_{\phi}^2(y)}{2} - lb log_{\phi}(y) - \frac{lc^2}{2} + lb lc\bigg]$$

Checking that the CDF is 1 at b,

$$G(b) = \frac{lc^2 - 2la lc + la^2}{(lc-la)(lb-la)} + \frac{-lb^2-lc^2+2lblc}{(lc-lb)(lb-la)}$$

$$G(b) = \frac{lc-la}{lb-la} + \frac{-(lc-lb)}{lb-la} = 1$$

Now calculating $E(y)$,

$$E(y) = \int y\ g(y)\ dy$$

$$=\frac{\beta_1}{ln({\phi})} \int_a^c \bigg[\frac{ln(y)}{ln({\phi})} - la\bigg]dy + 
\frac{\beta_2}{ln({\phi})} \int_c^b \bigg[\frac{ln(y)}{ln({\phi})} - lb]dy$$

$$=\frac{\beta_1}{ln({\phi})} \bigg[\frac{yln(y)-y}{ln({\phi})} - lay\bigg]_a^c +
\frac{\beta_2}{ln({\phi})} \bigg[\frac{yln(y)-y}{ln({\phi})} - lby\bigg]_c^b$$

$$=\frac{\beta_1}{ln({\phi})} \bigg[\frac{cln(c)-c}{ln({\phi})} - cla - \frac{aln(a)-a}{ln({\phi})} + ala\bigg] +
\frac{\beta_2}{ln({\phi})} \bigg[\frac{bln(b)-b}{ln({\phi})} - blb - \frac{cln(c)-c}{ln({\phi})} + clb\bigg]$$

$$=\frac{\beta_1}{ln({\phi})} \bigg[clc - \frac{c}{ln({\phi})} - cla + \frac{a}{ln({\phi})}\bigg] + \frac{\beta_2}{ln({\phi})} \bigg[\frac{-b}{ln({\phi})} - clc + \frac{c}{ln({\phi})} + clb\bigg]$$

